import 'package:home_services_app/features/service_request/data/models/service_details_model.dart';

final List<ServiceDetailsModel> servicesList = [
  ServiceDetailsModel(
    title: 'Plumbing',
    subTitle: 'Plumbing Service',
    imagePath: 'assets/images/plumbing_icon.png',
    description: 'We provide high-quality plumbing services for homes and offices.',
    features: ['Faucet installation', 'Leak repair', 'Pipe cleaning'],
    price: '150 EGP',
    estimatedDuration: '30 mins - 2 hrs',
    workingHours: '9:00 AM - 9:00 PM',
  ),
  ServiceDetailsModel(
    title: 'Carpentry',
    subTitle: 'Carpentry Service',
    imagePath: 'assets/images/carpentry.png',
    description: 'Expert carpentry services for furniture and woodwork.',
    features: ['Door repair', 'Furniture assembly', 'Wood polishing'],
    price: '200 EGP',
    estimatedDuration: '1 - 3 hrs',
    workingHours: '10:00 AM - 8:00 PM',
  ),
  ServiceDetailsModel(
    title: 'Electrical',
    subTitle: 'Electrical Service',
    imagePath: 'assets/images/electrical_icon.png',
    description: 'Professional electrical solutions for all your needs.',
    features: ['Socket installation', 'Wiring', 'Appliance repair'],
    price: '180 EGP',
    estimatedDuration: '30 mins - 2 hrs',
    workingHours: '8:00 AM - 10:00 PM',
  ),
  ServiceDetailsModel(
    title: 'Painting',
    subTitle: 'Painting Service',
    imagePath: 'assets/images/painting_icon.png',
    description: 'Interior and exterior painting with high-quality materials.',
    features: ['Wall painting', 'Ceiling painting', 'Decorative finishes'],
    price: '250 EGP',
    estimatedDuration: '2 - 5 hrs',
    workingHours: '9:00 AM - 6:00 PM',
  ),
  ServiceDetailsModel(
    title: 'Pest Control',
    subTitle: 'Pest Control Service',
    imagePath: 'assets/images/Pest_control_icon.png',
    description: 'Safe and effective pest control for homes and offices.',
    features: ['Ant control', 'Cockroach removal', 'Rodent management'],
    price: '300 EGP',
    estimatedDuration: '1 - 2 hrs',
    workingHours: '10:00 AM - 5:00 PM',
  ),
  ServiceDetailsModel(
    title: 'Cleaning',
    subTitle: 'Cleaning Service',
    imagePath: 'assets/images/cleaning_icon.png',
    description: 'Comprehensive cleaning services by trained professionals.',
    features: ['Home cleaning', 'Office cleaning', 'Deep cleaning'],
    price: '100 EGP',
    estimatedDuration: '1 - 3 hrs',
    workingHours: '7:00 AM - 9:00 PM',
  ),
];
